// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp6IKs6NDoWV3KWynbJqsAGqzCk_V5KiA',
    appId: '1:15978137406:web:7cf8e6b35469d932aa8e6f',
    messagingSenderId: '15978137406',
    projectId: 'anihub-d83a6',
    authDomain: 'anihub-d83a6.firebaseapp.com',
    storageBucket: 'anihub-d83a6.appspot.com',
    measurementId: 'G-JTK5VSFWR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSPtzJLqCk-R7lojjRdqT523p9N7vkkE',
    appId: '1:15978137406:android:55ed7e9a68c2511eaa8e6f',
    messagingSenderId: '15978137406',
    projectId: 'anihub-d83a6',
    storageBucket: 'anihub-d83a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rOijLur_EOU-XWUELBX72I5X8PaVlgI',
    appId: '1:15978137406:ios:b48bf01c2f246532aa8e6f',
    messagingSenderId: '15978137406',
    projectId: 'anihub-d83a6',
    storageBucket: 'anihub-d83a6.appspot.com',
    iosBundleId: 'com.example.anihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rOijLur_EOU-XWUELBX72I5X8PaVlgI',
    appId: '1:15978137406:ios:b48bf01c2f246532aa8e6f',
    messagingSenderId: '15978137406',
    projectId: 'anihub-d83a6',
    storageBucket: 'anihub-d83a6.appspot.com',
    iosBundleId: 'com.example.anihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp6IKs6NDoWV3KWynbJqsAGqzCk_V5KiA',
    appId: '1:15978137406:web:48e4a8809425646faa8e6f',
    messagingSenderId: '15978137406',
    projectId: 'anihub-d83a6',
    authDomain: 'anihub-d83a6.firebaseapp.com',
    storageBucket: 'anihub-d83a6.appspot.com',
    measurementId: 'G-CSLS3SE18B',
  );
}
